baseURL = "https://tomkiel.com.br"
theme = "tomkiel"
defaultContentLanguage = "pt-br"
enableRobotsTXT = true

[languages]
[languages.pt-br]
title = "Regis Tomkiel"
biography = "Sou desenvolvedor de software e entusiasta de Software Livre/Open Source na horas vagas."
description = ""
pexelsBiography = "Conheça mais sobre mim com minhas fotos no Pexels (Sem royalties)."
languageCode = "pt-br"
languageName = "Português"
contentDir = "content/portuguese"
weight = 1

[[languages.pt-br.menu.free_software]]
name = "Ubuntu"
identifier = "ubuntu"
weight = 1
url = "/"

[[languages.pt-br.menu.development]]
name = "Python"
identifier = "python"
weight = 1
url = "/"


[languages.en]
title = "Regis Tomkiel"
biography = "I'm a software developer and Free/Open Source enthusiast in my free time."
description = ""
pexelsBiography = "Know more about me with my photos on Pexels (No royalties)"
languageCode = "en"
languageName = "English"
contentDir = "content/english"
weight = 2

[[languages.en.menu.free_software]]
name = "Ubuntu"
identifier = "ubuntu"
weight = 1
url = "/"

[[languages.en.menu.development]]
name = "Python"
identifier = "python"
weight = 1
url = "/"


[languages.pl-pl]
title = "Regis Tomkiel"
biography = "W wolnym czasie jestem programistą i entuzjastą Wolnego/Otwartego Oprogramowania."
description = ""
pexelsBiography = "Zobacz więcej o mnie z moimi zdjęciami na Pexels (Bez praw autorskich)"
languageCode = "pl-pl"
languageName = "Polski"
contentDir = "content/polish"
weight = 2

[[languages.pl-pl.menu.free_software]]
name = "Ubuntu"
identifier = "ubuntu"
weight = 1
url = "/"

[[languages.pl-pl.menu.development]]
name = "Python"
identifier = "python"
weight = 1
url = "/"


[permalinks]
fixed = ":title/"
blog = ":slug"
pages = ":slug"

[taxonomies]
tag = "tags"
category = "categories"

[params]
author = "Regis Tomkiel"
avatar = "tomkiel"
avatarFallback = "https://avatars2.githubusercontent.com/u/15989303?s=400&u=9eb0f3fdfa13bc817d392cecd23966f4ec51fea2&v=4"
gravatar = "https://1.gravatar.com/avatar/d3f106548d6d0c62e817c5884a9474583564a8625693df35726a22b890ba765f?s=400&d=mm"
email = "me@tomkiel.com.br"
city = "Caxias do Sul"
image = "images/tomkiel.jpg"
gtag = "G-YRW7Z15SDD"

[params.contact]
youtube = "https://www.youtube.com/c/TomkielTV"
twitter = "https://twitter.com/tomtomkiel"
github = "https://github.com/tomkiel"
linkedin = "https://www.linkedin.com/in/regis-tomkiel/"
instagram = "https://www.instagram.com/registomkiel/"

[params.pexels]
[params.pexels.author]
name = "@regis-tomkiel"
avatar = "https://images.pexels.com/users/avatars/167936/regis-tomkiel-120.jpeg?auto=compress&fit=crop&h=56&w=56"
profile = "@regis-tomkiel-167936"

[[params.pexels.pictures]]
id = "9366533"
namePt = "camiseta-preta-homem-metal-fundo-da-natureza"
nameEn = "man-metal-nature-background-rock-and-roll"

[[params.pexels.pictures]]
id = "11204690"
namePt = "apartamento-arquitetura-construcao-predio"
nameEn = "to do"

[[params.pexels.pictures]]
id = "5762079"
namePt = "caminhada-trilha-cor-da-natureza-estilo-de-rua"
nameEn = "hiking-nature-color-street-style-nature"

[[params.pexels.pictures]]
id = "5762822"
namePt = "azul-celeste-ceu-azul-indigo-ceu-de-brigadeiro"
nameEn = "ambience-coniferous-trees-azure-nature"

[[params.pexels.pictures]]
id = "9366504"
namePt = "homem-metal-apontando-tatuagem"
nameEn = "man-metal-tattoo-pointing"

[[params.pexels.pictures]]
id = "11204685"
namePt = "samambaia-fotografia-da-natureza-parque-america-do-sul"
nameEn = "park-fern-nature-photography-south-america"

[params.youtube]
channel = "UC-lHJZR3Gqxm24_Vd_AJ5Yw"
avatar = ""

[[params.youtube.videos]]
id = "FVOfpx1g8NY"

[[params.youtube.videos]]
id = "4ozqIpd1B3Q"

[[params.youtube.videos]]
id = "8GM-p1ev40g"

[[params.youtube.videos]]
id = "sSrpxaKG764"

[[params.youtube.videos]]
id = "0odzW4GATCI"

[[params.youtube.videos]]
id = "A1Vd7HuvmIg"