name = "tomkiel"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Regis Tomkiel<me@tomkiel.com.br>"
  homepage = "https://tomkiel.com.br"
